### ISSUE TITLE
Separate Simulator enum

### ISSUE THREAD

**Issue by JulesMoorhouse** [giuseppenucifora/UIDevice-Utils#2]
It would be awesome the device model could be returned from the simulator rather that iPadSimulator etc.

**Comment by giuseppenucifora** [comment]
You wish you could understand if the simulator is a specific device?

Thx
Giuseppe

**Comment by JulesMoorhouse** [comment]
No, I want to know which device is being simulated using the existing device values.

Basically I want to write code for a specific device and see the results in the simulator. Getting a device type of simulator doesn't help me.

Thanks for your help.

**Comment by giuseppenucifora** [comment]
If you want to distinguish between different devices when you use simulator you can use UIDeviceModelInches enum to get different size of screen. There isn't a method to know perfectly which device the simulator run.

You might try something like this :

``` objc
switch ([[UIDevice currentDevice] deviceFamily]) {
        case UIDeviceFamilyiPhone:
        case UIDeviceFamilyiPod: {

            switch ([[UIDevice currentDevice] deviceInches]) {
                case UIDeviceModelInches35: {

                    break;
                }
                case UIDeviceModelInches4: {

                    break;
                }
                case UIDeviceModelInches47: {

                    break;
                }
                case UIDeviceModelInches55: {

                    break;
                }
                case UIDeviceModelInchesUnKnown:
                default: {
                    break;
                }
            }
            break;
        }
        case UIDeviceFamilyiPad: {
            switch ([[UIDevice currentDevice] deviceInches]) {

                case UIDeviceModelInches79: {

                    break;
                }
                case UIDeviceModelInches97: {

                    break;
                }
                case UIDeviceModelInches129: {

                    break;
                }
                case UIDeviceModelInchesUnKnown:
                default: {
                    break;
                }
            }
            break;
        }
        default: {
            break;
        }
    }
```

**Comment by JulesMoorhouse** [comment]
Oh right, is that part of your library?

**Comment by giuseppenucifora** [comment]
Yes, you can copy and paste the code :)

**Comment by InderKumarRathore** [comment]
Ah that can be done by checking the screen height or width as well, but this will tell you the screen size, it won't be able to tell you if your device is 5 or 5s :)

**Comment by JulesMoorhouse** [comment]
Hi,

If your using the simulator UIDeviceModelInches129 is never reached, UIDeviceModelInchesUnKnown is returned.

I can see that the x86_64 derived and condition is reached that determines if its a small screen or big screen.

Can this be improved in anyway?

I'm not likely to have any access to an iPad pro and I will have rely on the simulator.

Thanks in advance.
